import type { Component } from 'svelte'
import {
  File as FileIcon,
  FileText,
  FileImage,
  FileVideo,
  FileAudio,
  FileArchive,
  FileSpreadsheet,
  FileType,
  FileLock,
  Database,
  Binary,
  Settings,
  Cog,
  BookText,
  GitBranch,
  Package,
  ScrollText,
  Hash,
  FileJson,
} from '@lucide/svelte'
import {
  siTypescript,
  siJavascript,
  siReact,
  siSvelte,
  siVuedotjs,
  siAstro,
  siPython,
  siRust,
  siGo,
  siC,
  siCplusplus,
  siOpenjdk,
  siKotlin,
  siScala,
  siRuby,
  siElixir,
  siPhp,
  siLua,
  siSwift,
  siDart,
  siHaskell,
  siHtml5,
  siCss,
  siSass,
  siLess,
  siTailwindcss,
  siDocker,
  siGit,
  siNpm,
  siYarn,
  siPnpm,
  siBun,
  siNodedotjs,
  siMarkdown,
  siToml,
  siYaml,
  siGnubash,
  siWebassembly,
  siMysql,
  siPostgresql,
  siSqlite,
  siTerraform,
  siGraphql,
  siProtocolsdotio,
  siGradle,
  siPrisma,
  siVite,
  siWebpack,
  siEslint,
  siPrettier,
  siEditorconfig,
} from 'simple-icons'
import type { SimpleIcon } from 'simple-icons'

export type FileIconInfo =
  | { kind: 'lucide'; Icon: Component; color: string }
  | { kind: 'brand'; path: string; color: string; title: string }

const DEFAULT_ICON: FileIconInfo = {
  kind: 'lucide',
  Icon: FileIcon,
  color: 'var(--color-text-muted)',
}

function brand(icon: SimpleIcon): FileIconInfo {
  return { kind: 'brand', path: icon.path, color: `#${icon.hex}`, title: icon.title }
}

const filenameMap: Record<string, FileIconInfo> = {
  dockerfile: brand(siDocker),
  'docker-compose.yml': brand(siDocker),
  'docker-compose.yaml': brand(siDocker),
  makefile: { kind: 'lucide', Icon: Cog, color: '#f59e0b' },
  'cmakelists.txt': { kind: 'lucide', Icon: Cog, color: '#f59e0b' },
  readme: { kind: 'lucide', Icon: BookText, color: '#519aba' },
  'readme.md': { kind: 'lucide', Icon: BookText, color: '#519aba' },
  license: { kind: 'lucide', Icon: ScrollText, color: '#f59e0b' },
  'license.md': { kind: 'lucide', Icon: ScrollText, color: '#f59e0b' },
  'package.json': brand(siNpm),
  'package-lock.json': brand(siNpm),
  'yarn.lock': brand(siYarn),
  'bun.lock': brand(siBun),
  'bun.lockb': brand(siBun),
  'pnpm-lock.yaml': brand(siPnpm),
  'cargo.toml': brand(siRust),
  'cargo.lock': brand(siRust),
  'go.mod': brand(siGo),
  'go.sum': brand(siGo),
  'pyproject.toml': brand(siPython),
  'poetry.lock': brand(siPython),
  'requirements.txt': brand(siPython),
  '.gitignore': brand(siGit),
  '.gitattributes': brand(siGit),
  '.gitmodules': brand(siGit),
  '.env': { kind: 'lucide', Icon: Settings, color: '#eab308' },
  '.env.local': { kind: 'lucide', Icon: Settings, color: '#eab308' },
  '.env.example': { kind: 'lucide', Icon: Settings, color: '#eab308' },
  '.editorconfig': brand(siEditorconfig),
  '.prettierrc': brand(siPrettier),
  '.prettierrc.json': brand(siPrettier),
  '.prettierrc.js': brand(siPrettier),
  '.eslintrc': brand(siEslint),
  '.eslintrc.json': brand(siEslint),
  'eslint.config.js': brand(siEslint),
  'eslint.config.mjs': brand(siEslint),
  'tsconfig.json': brand(siTypescript),
  'tsconfig.node.json': brand(siTypescript),
  'tsconfig.web.json': brand(siTypescript),
  'vite.config.ts': brand(siVite),
  'vite.config.js': brand(siVite),
  'vite.config.mjs': brand(siVite),
  'webpack.config.js': brand(siWebpack),
  'svelte.config.js': brand(siSvelte),
  'svelte.config.ts': brand(siSvelte),
  'tailwind.config.js': brand(siTailwindcss),
  'tailwind.config.ts': brand(siTailwindcss),
  'postcss.config.js': brand(siCss),
  'gradle.build': brand(siGradle),
  'build.gradle': brand(siGradle),
  'schema.prisma': brand(siPrisma),
}

const extMap: Record<string, FileIconInfo> = {
  // TypeScript / JavaScript
  ts: brand(siTypescript),
  tsx: brand(siReact),
  mts: brand(siTypescript),
  cts: brand(siTypescript),
  d: brand(siTypescript),
  js: brand(siJavascript),
  jsx: brand(siReact),
  mjs: brand(siJavascript),
  cjs: brand(siJavascript),
  // Frameworks
  svelte: brand(siSvelte),
  vue: brand(siVuedotjs),
  astro: brand(siAstro),
  // Other languages
  py: brand(siPython),
  pyi: brand(siPython),
  rs: brand(siRust),
  go: brand(siGo),
  c: brand(siC),
  h: brand(siC),
  cpp: brand(siCplusplus),
  cc: brand(siCplusplus),
  cxx: brand(siCplusplus),
  hpp: brand(siCplusplus),
  hxx: brand(siCplusplus),
  java: brand(siOpenjdk),
  kt: brand(siKotlin),
  kts: brand(siKotlin),
  scala: brand(siScala),
  rb: brand(siRuby),
  ex: brand(siElixir),
  exs: brand(siElixir),
  php: brand(siPhp),
  lua: brand(siLua),
  swift: brand(siSwift),
  dart: brand(siDart),
  hs: brand(siHaskell),
  // Markup / styles
  html: brand(siHtml5),
  htm: brand(siHtml5),
  css: brand(siCss),
  scss: brand(siSass),
  sass: brand(siSass),
  less: brand(siLess),
  // Data / config
  json: { kind: 'lucide', Icon: FileJson, color: '#cbcb41' },
  jsonc: { kind: 'lucide', Icon: FileJson, color: '#cbcb41' },
  json5: { kind: 'lucide', Icon: FileJson, color: '#cbcb41' },
  yaml: brand(siYaml),
  yml: brand(siYaml),
  toml: brand(siToml),
  ini: { kind: 'lucide', Icon: Hash, color: '#888888' },
  env: { kind: 'lucide', Icon: Settings, color: '#eab308' },
  xml: { kind: 'lucide', Icon: Hash, color: '#0060ac' },
  graphql: brand(siGraphql),
  gql: brand(siGraphql),
  proto: brand(siProtocolsdotio),
  tf: brand(siTerraform),
  // Markdown / docs
  md: brand(siMarkdown),
  mdx: brand(siMarkdown),
  txt: { kind: 'lucide', Icon: FileText, color: 'var(--color-text-muted)' },
  rst: { kind: 'lucide', Icon: FileText, color: '#888' },
  log: { kind: 'lucide', Icon: FileText, color: '#888' },
  // Shell
  sh: brand(siGnubash),
  bash: brand(siGnubash),
  zsh: brand(siGnubash),
  fish: brand(siGnubash),
  ps1: { kind: 'lucide', Icon: Settings, color: '#012456' },
  bat: { kind: 'lucide', Icon: Settings, color: '#888' },
  // DB
  sql: { kind: 'lucide', Icon: Database, color: '#dad8d8' },
  mysql: brand(siMysql),
  pgsql: brand(siPostgresql),
  db: { kind: 'lucide', Icon: Database, color: '#dad8d8' },
  sqlite: brand(siSqlite),
  sqlite3: brand(siSqlite),
  // Images
  png: { kind: 'lucide', Icon: FileImage, color: '#a074c4' },
  jpg: { kind: 'lucide', Icon: FileImage, color: '#a074c4' },
  jpeg: { kind: 'lucide', Icon: FileImage, color: '#a074c4' },
  gif: { kind: 'lucide', Icon: FileImage, color: '#a074c4' },
  svg: { kind: 'lucide', Icon: FileImage, color: '#ffb13b' },
  webp: { kind: 'lucide', Icon: FileImage, color: '#a074c4' },
  ico: { kind: 'lucide', Icon: FileImage, color: '#a074c4' },
  bmp: { kind: 'lucide', Icon: FileImage, color: '#a074c4' },
  // Video
  mp4: { kind: 'lucide', Icon: FileVideo, color: '#fd971f' },
  mov: { kind: 'lucide', Icon: FileVideo, color: '#fd971f' },
  mkv: { kind: 'lucide', Icon: FileVideo, color: '#fd971f' },
  webm: { kind: 'lucide', Icon: FileVideo, color: '#fd971f' },
  // Audio
  mp3: { kind: 'lucide', Icon: FileAudio, color: '#ec407a' },
  wav: { kind: 'lucide', Icon: FileAudio, color: '#ec407a' },
  ogg: { kind: 'lucide', Icon: FileAudio, color: '#ec407a' },
  flac: { kind: 'lucide', Icon: FileAudio, color: '#ec407a' },
  // Archives
  zip: { kind: 'lucide', Icon: FileArchive, color: '#afa700' },
  tar: { kind: 'lucide', Icon: FileArchive, color: '#afa700' },
  gz: { kind: 'lucide', Icon: FileArchive, color: '#afa700' },
  '7z': { kind: 'lucide', Icon: FileArchive, color: '#afa700' },
  rar: { kind: 'lucide', Icon: FileArchive, color: '#afa700' },
  // Binaries / fonts
  exe: { kind: 'lucide', Icon: Binary, color: '#888' },
  dll: { kind: 'lucide', Icon: Binary, color: '#888' },
  so: { kind: 'lucide', Icon: Binary, color: '#888' },
  dylib: { kind: 'lucide', Icon: Binary, color: '#888' },
  bin: { kind: 'lucide', Icon: Binary, color: '#888' },
  wasm: brand(siWebassembly),
  ttf: { kind: 'lucide', Icon: FileType, color: '#888' },
  otf: { kind: 'lucide', Icon: FileType, color: '#888' },
  woff: { kind: 'lucide', Icon: FileType, color: '#888' },
  woff2: { kind: 'lucide', Icon: FileType, color: '#888' },
  // Spreadsheets / docs
  csv: { kind: 'lucide', Icon: FileSpreadsheet, color: '#1d6f42' },
  xlsx: { kind: 'lucide', Icon: FileSpreadsheet, color: '#1d6f42' },
  tsv: { kind: 'lucide', Icon: FileSpreadsheet, color: '#1d6f42' },
  pdf: { kind: 'lucide', Icon: FileText, color: '#cc342d' },
  // Node
  node: brand(siNodedotjs),
  // Lock / misc
  lock: { kind: 'lucide', Icon: FileLock, color: '#888' },
  // AI / ML
  safetensors: { kind: 'lucide', Icon: Binary, color: '#888' },
  onnx: { kind: 'lucide', Icon: Binary, color: '#888' },
  ipynb: brand(siPython),
  gguf: { kind: 'lucide', Icon: Binary, color: '#10a37f' },
  // Branch pointer
  branch: { kind: 'lucide', Icon: GitBranch, color: '#f05033' },
  // package
  pkg: { kind: 'lucide', Icon: Package, color: '#888' },
}

export function getFileIcon(filePath: string): FileIconInfo {
  const base = (filePath.split('/').pop() ?? filePath).toLowerCase()
  const named = filenameMap[base]
  if (named) return named
  const dotIdx = base.lastIndexOf('.')
  if (dotIdx < 0) return DEFAULT_ICON
  const ext = base.slice(dotIdx + 1)
  return extMap[ext] ?? DEFAULT_ICON
}
